### ISSUE TITLE
After compiling the exe `Failed to execute script`

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#12]
@wan-joe 

>After compiling the exe doesn't work when i click on it or from command prompt
>`Failed to execute script`

Got one step back, verify if it works without compiling.

**Comment by wan-joe** [comment]
Yeah it works without compiling

@WK-GiHu

**Comment by WK-GiHu** [comment]
@wan-joe 

> Yeah it works without compiling

Start the compiled version from `command prompt` and show **all** output you are getting.

**Comment by wan-joe** [comment]
@WK-GiHu 

Same error at the command prompt

**Comment by WK-GiHu** [comment]
@wan-joe 

> Same error at the command prompt

This is expected behavior!

# I have to see the output
# **ALL** output!

**Comment by wan-joe** [comment]
It doesn't print the output when i run it at command prompt.

@WK-GiHu

**Comment by WK-GiHu** [comment]
@wan-joe 

>

Make a test one, **only** the following lines:

    if __name__ == '__main__':
        import psutil, os
    
        PROCNAME = __file__
        PID = os.getpid()
        print('PROCNAME:{} PID:{}'.format(PROCNAME, PID))

Did you see the `PROCNAME...` output?

**Comment by wan-joe** [comment]
I see the output when i run the script but when i compile it doesn't print it at the command prompt.

**Comment by WK-GiHu** [comment]
@wan-joe 

>  when i compile it doesn't print it at the command prompt.

Are you sure, you run it from `command prompt`?

- [x] Show your `pyinstaller` command line

**Comment by wan-joe** [comment]
Yeah am running it from command prompt.

`pyinstaller --windowed --onefile  myapp.py`

**Comment by WK-GiHu** [comment]
@wan-joe 

> For Windows, you will need to re-bundle your application without the --windowed option. Then you can run the resulting executable from the command line.

Change to `pyinstaller --debug=all --onefile myapp.py` and see if you'r getting any output.

**Comment by wan-joe** [comment]
I didn't add `--windowed` to the `pyinstaller command` getting this error

`NameError : "exit" not defined`

**Comment by WK-GiHu** [comment]
@wan-joe 

> NameError : "exit" not defined

Change to:

    import psutil, os, sys
    ...
    sys.exit(None)

**Comment by wan-joe** [comment]
@WK-GiHu 
It doesn't open after compiling 
No errors too.

**Comment by WK-GiHu** [comment]
>

**Comment by wan-joe** [comment]
@WK-GiHu 
Any update from you

**Comment by WK-GiHu** [comment]
@wan-joe 

>Any update from you

If a `Issue` get closed, click on `[Issues]` at the top to see **New** Issues.
I wonder you got no Notification, because i notified you with @wan-joe?

**Comment by WK-GiHu** [comment]
Still 

> `Traceback (most recent call last):
  File "myapp.py", line 30, in <module>
NameError: name 'exit' is not defined'
>
>after running it from cmd
