### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add'

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#18]
@WK-GiHu 

```
    parent.add(proc.pid)
AttributeError: 'NoneType' object has no attribute 'add'
```

Getting another error.

_Originally posted by @wan-joe in https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-582506656_

**Comment by WK-GiHu** [comment]
@wan-joe 

Fixed: Merge https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/pull/17

**Comment by wan-joe** [comment]
@WK-GiHu


Am getting another error 

  ```
 name = _parent['name']
TypeError: 'Process' object is not subscriptable
```

**Comment by WK-GiHu** [comment]
@wan-joe 
>TypeError: 'Process' object is not subscriptable

Merge https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/pull/19

Cant't finde the reason for `TypeError: 'Process' object is not subscriptable.`
### Need the output of the print statements

**Comment by wan-joe** [comment]
This is the print statements
```
PROCNAME:myapp.exe PID:2484
_parent:<class 'NoneType'> None
_parent[name]:unknown
_parent:<class 'psutil.Process'> psutil.Process(pid=0, name='System Idle Process', started='00:42:46')
```
Am getting the error:

  ```
 name = _parent['name']
TypeError: 'Process' object is not subscriptable

```

**Comment by WK-GiHu** [comment]
@wan-joe 

>TypeError: 'Process' object is not subscriptable

Fixed, merge: https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/pull/20

**Comment by wan-joe** [comment]
@WK-GiHu 

The app opens now after compiling, it gives no error when i first run it but when i double on it to run it for the second time whiles the first run is not closed i get the this error  `failed to execute script myapp`.

 I have attached image for you to see
![frs](https://user-images.githubusercontent.com/50240352/74763744-35f1ba00-5235-11ea-83f8-645c25cb04d5.PNG)

**Comment by WK-GiHu** [comment]
@wan-joe 

>for the second time whiles the first run is not closed i get the this error failed to execute script myapp.

I need the **console** output of the **second run**.

**Comment by wan-joe** [comment]
@WK-GiHu 


This is for first run :

```
PROCNAME:myapp.exe PID:3716
child:{3716}, parent={0, 4, 2060, 1044, 2580, 7188, 1060, 1072, 2608, 6716, 1604, 5700, 3144, 4176, 3156, 5204, 6740, 61
6, 1128, 2152, 3180, 624, 116, 3188, 636, 3200, 2184, 2708, 5284, 4264, 5292, 6316, 692, 4788, 5812, 1212, 1724, 2236, 7
12, 1736, 2760, 6860, 3288, 2272, 1764, 748, 5876, 760, 768, 772, 776, 7436, 1812, 5908, 4376, 3868, 5408, 1316, 2340, 4
912, 832, 1344, 3904, 1352, 3412, 5976, 356, 4452, 1896, 8044, 1908, 2420, 1404, 1928, 1424, 3984, 6544, 916, 6056, 6064
, 1992, 7644, 5092, 6128, 6140}, running:set()
```

second run  : 

```
PROCNAME:myapp.exe PID:5736
child:{5736, 3716}, parent={0, 768, 3200, 4, 772, 776, 1928, 2184, 2060, 7436, 1424, 3984, 916, 1044, 1812, 2580, 1404,
2708, 4376, 5908, 3868, 7188, 5408, 1060, 1316, 2340, 5284, 4264, 6056, 5292, 6140, 6316, 2608, 4912, 6064, 692, 4788, 5
812, 1212, 1724, 2236, 6716, 832, 1344, 3904, 1604, 5700, 712, 1352, 1736, 1992, 2760, 3144, 6860, 4176, 3156, 3412, 430
8, 6740, 3288, 5976, 5724, 2272, 356, 1764, 4452, 5092, 616, 1128, 1896, 2152, 748, 3180, 6760, 8044, 624, 6128, 116, 19
08, 2420, 3188, 760, 5876, 636}, running:{3716}
Traceback (most recent call last):
  File "myapp.py", line 53, in <module>
NameError: name 'running' is not defined
[5736]Failed to execute script myapp
```

**Comment by WK-GiHu** [comment]
@wan-joe 

>`NameError: name 'running' is not defined`

Should be read: `print('EXIT: running:{}'.format(exit_running))`

**Comment by wan-joe** [comment]
@WK-GiHu 

It is working now thanks for your continuous support.

**Comment by WK-GiHu** [comment]
@wan-joe 

>It is working now

OK, I feel happy about it too.
