### ISSUE TITLE
import tkinter 

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#2]
@wan-joe 

Move this line 
https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/131090bbc3d5a25f6743780227df1a435e915ca2/TKINETER%20APP%20ONCE#L2
to line 21

**Comment by wan-joe** [comment]
Have done the changes

**Comment by WK-GiHu** [comment]
@wan-joe 
> Have done the changes

Looks OK, will it work for you?

**Comment by wan-joe** [comment]
It doesn't work when i compile the script.

**Comment by WK-GiHu** [comment]
@wan-joe 

> It doesn't work when i compile the script.

Show how you do "compile the script" and show any **Traceback** Error you get.
