### ISSUE TITLE
It doesn't work when i compile the script.

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#4]
@wan-joe 

> It doesn't work when i compile the script.

Show how you do "compile the script" and show any **Traceback** Error you get.

**Comment by wan-joe** [comment]
after compiling with pyinstaller and run the exe file i get `fiailed to execute script` but when i remove `psutil` part
it works perfectly.

**Comment by WK-GiHu** [comment]
@wan-joe 
> compiling with pyinstaller and run the exe file i get `fiailed to execute script` but when i remove psutil part it works perfectly.

So, `pyinstaller` ist missing `psutil`. 
You have to add `psutil` into your config to tell  `pyinstaller` to include it.
Read [spec-file-operation](https://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=pure#spec-file-operation)

Are you using?

    a = Analysis(['myPython.py'],
             pathex=

you have to add the path to `psutil` to `pathex=`

Read [pyinstaller-package-python-applications-windows-mac-linux/](https://www.pythoncentral.io/pyinstaller-package-python-applications-windows-mac-linux/) to get a brief description using `hiddenimports=[],`.

**Comment by wan-joe** [comment]
Am not using this   
`a = Analysis(['myPython.py'],
         pathex=`

what i does is `pyinstaller --windowed --onefile myscript.py`

Have gone through the link you posted but sorry to say am not able to do what is how described in the link . How am going to add the third party imports.

Can you break it down for me if possible how am going to  write the `pyinstaller` script command to compile it.

Did this:

`pyinstaller --windowed --onefile --hidden-import=psutil   myapp.py`

but still getting same error:

 `failed to execute script`

**Comment by WK-GiHu** [comment]
@wan-joe 

> Did this:
> pyinstaller --windowed --onefile --hidden-import=psutil myapp.py
> but still getting same error: failed to execute script

The error message is not meaningfull at all:
Try to get more info about the reason of the error, Use [--debug=...](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?highlight=debug):

    pyinstaller --debug=all --windowed --onefile --hidden-import=psutil myapp.py

or

    pyinstaller --debug=imports --windowed --onefile --hidden-import=psutil myapp.py

**Comment by wan-joe** [comment]
Have added the `debug`  option to it but output messages like running myapp.exe then it outputs `failed to execute script my app`

Have attached the zip file containing the script and the executable to it.

link to the files: https://drive.google.com/open?id=1HjgMzDO-rzOC1ZHsmeb8NfwI2xMFXwFV

**Comment by WK-GiHu** [comment]
@wan-joe 
> Have attached the zip file containing the script and the executable to it.

Got it and found "psutil" is inside the exe archive.
Therefore, there must be another reason.

Without more detailed error message, I can't help.
[do ask for assistance on the PyInstaller Email List.](https://groups.google.com/forum/#!forum/pyinstaller)

Try this workaround, replace `psutil` with `WMI`

    import wmi
    c = wmi.WMI ()
    for process in c.Win32_Process ():
         if PROCNAME in process.Name:
             print (process.ProcessId, process.Name)

**Comment by wan-joe** [comment]
Thanks for the feedback what i found is when i remove `exit(1)`  the `exe` run without error but i can open the several times.

So i change the `exit(1)` to `sys.exit(1)` but the app doesn't open at all.

I did the `wmi` one but i can open the several times without error

**Comment by WK-GiHu** [comment]
@wan-joe 
> Thanks for the feedback what i found is when i remove exit(1) the exe run without error but i can open the several times.

This is expected behavior, because `exit(...` is the call **not** to continue.
Did you always, first `exe` run, second time `exe` run, get the output?

    print("Running, exit(1).")

>   when i remove exit(1) the exe run without error 

Ahhhh, this is the culprit.
Doing `exit(1)` results in `failed to execute script my app` because a return code of `1` indicates a failure. Change to `exit(0)`.

**Comment by wan-joe** [comment]
same error `failed to execute script myapp` when i change it `exit(0)`

**Comment by WK-GiHu** [comment]
@wan-joe 
> So i change the exit(1) to sys.exit(1) but the app doesn't open at all.

Did you always, first time exe run, second time exe run, get the output?

    print("Running, exit(1).")

See my `Pull Request`, fixing logic error.

---

**Comment by wan-joe** [comment]
No it prints `not running, continue to startup.` when i open it several times

**Comment by WK-GiHu** [comment]
@wan-joe 

## What about my `Pull request`?

Try and comment!

**Comment by wan-joe** [comment]
Don't understand what you mean by `pull request`

**Comment by WK-GiHu** [comment]
> Don't understand what you mean by pull request

On TOP of your GitHub Page there you can see

    Code Issues 1 Pull requests 1 Projects 0 Security Insights

Click on `Pull request` and see my `Code` changes.
Try this `code` and comment
