### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#6]
@wan-joe 

> Am getting error `TypeError: argument of type 'NoneType' is not iterable` from this section of the code `if PROCNAME in info['cmdline'] and PID != info['pid']:` when i run the code.

Your `psutil` behave different.
Read [psutil.process_iter](https://psutil.readthedocs.io/en/latest/#psutil.process_iter) and setup a test `app` to see what you get from the linked Example code.

**Comment by wan-joe** [comment]
This how my output is displayed when i run the example code in the link you provided. Also found out that you can have more than two `pid ` for an application .

```
{'username': 'MARW\\MARW-LAP1', 'pid': 2916, 'name': 'dllhost.exe'}
{'username': None, 'pid': 2936, 'name': 'svchost.exe'}
{'username': 'MARW\\MARW-LAP1', 'pid': 3096, 'name': 'acrotray.exe'}
{'username': 'MARW\\MARW-LAP1', 'pid': 16972, 'name': 'opera.exe'}
{'username': 'MARW\\MARW-LAP1', 'pid': 17336, 'name': 'Adobe Desktop Service.exe'}
```

**Comment by WK-GiHu** [comment]
@wan-joe 

>`TypeError: argument of type 'NoneType' is not iterable`

  - [x] Show the FULL Traceback, there must be another reason about the `TypeError`

---

>This how my output is displayed when i run the example code in the link you provided. 
>`{'username': 'MARW\\MARW-LAP1', 'pid': 16972, 'name': 'opera.exe'}`

Looks good, but

  - [x] Show the output with **THIS** attributes: `['pid', 'name', 'cmdline']` and the line we interested in.
  - [x] Show the output of ` print('PROCNAME:{} PID:{}'.format(PROCNAME, PID))`

**Comment by wan-joe** [comment]
Print output
`PROCNAME:C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py PID:73236`


Error traceback

```
Traceback (most recent call last):
  File "C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py", line 73, in <module>
    if info and PROCNAME in info['cmdline'] and PID != info['pid']:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by WK-GiHu** [comment]
@wan-joe 

[Missing requested output from this comment!](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/6#issuecomment-514189536)

---

>Traceback (most recent call last):
  File "C:/.../APP.py", line 73, in <module>

There is **NO** `line 73`!
Please run the Code as shown in `/TKINETER APP ONCE` right away in Pycharm and show the Traceback.

**Comment by wan-joe** [comment]
```
[Traceback (most recent call last):
  File "C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py", line 25, in <module>
    if info and PROCNAME in info['cmdline'] and PID != info['pid']:
TypeError: argument of type 'NoneType' is not iterable](url)
```

**Comment by WK-GiHu** [comment]
@wan-joe 

[Still missing requested output from this comment!](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/6#issuecomment-514189536)

---

The `Traceback` makes no sense?
There ist no **iteration** in line `25`!
If `info` is `None` the `Traceback` should read:

    TypeError: 'NoneType' object is not subscriptable

**Where does the `(url)` in `...not iterable](url)` come from?**
---

Enable the following line and show the output **before** the `Traceback`

https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/3618151126172222390177acb627bbd57afce327/TKINETER%20APP%20ONCE#L23

**Comment by wan-joe** [comment]
This is the output

```
info:{'name': 'System Idle Process', 'pid': 0, 'cmdline': []}
info:{'name': 'System', 'pid': 4, 'cmdline': []}
info:{'name': 'Registry', 'pid': 96, 'cmdline': None}
```

**Comment by WK-GiHu** [comment]
@wan-joe 

Found the reason about `TypeError: argument of type 'NoneType' is not iterable`.
# Merge my **Pull request**

**Comment by wan-joe** [comment]
It doesn't give error now but can open the app several times after compiling 

![img](https://user-images.githubusercontent.com/50240352/61954521-8b6c2e00-afa8-11e9-8426-0edb8dd4d251.PNG)
