### ISSUE TITLE
can open the app several times

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#8]
@wan-joe 

> It doesn't give error now but can open the app several times after compiling

Got one step back, **first** we have to verify if it works **without** compiling.
You have to accept, that running from different starters, e.g. PyCharm, Windows Desktop Link or compiled the `info['cmdline']` differs. 

---

**Show allways** the output from `PROCNAME:C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py PID:73236` 
# and
the output from `print('info:{}'.format(info))`

your are getting. You have to find a **matching** pattern in `info['cmdline']`.

---

 - Running multiple times from PyCharm
    - [ ] Open multiple windows
    - [x] Open only once

**Comment by wan-joe** [comment]
`PROCNAME:C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py PID:260628`

Then print all the process running

```
info:{'pid': 2936, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3264, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3356, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3400, 'name': 'spoolsv.exe', 'cmdline': None}
info:{'pid': 3596, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3692, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3784, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3828, 'name': 'EvoPCSvc.exe', 'cmdline': None}
info:{'pid': 3884, 'name': 'unsecapp.exe', 'cmdline': None}
info:{'pid': 3892, 'name': 'armsvc.exe', 'cmdline': None}
info:{'pid': 3900, 'name': 'AGMService.exe', 'cmdline': None}
info:{'pid': 3924, 'name': 'AdobeUpdateService.exe', 'cmdline': None}
info:{'pid': 3932, 'name': 'EvoPCSvc.exe', 'cmdline': None}
info:{'pid': 3940, 'name': 'AGSService.exe', 'cmdline': None}
info:{'pid': 3948, 'name': 'AvansiaSV.EXE', 'cmdline': None}
info:{'pid': 3956, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3980, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 3988, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 4020, 'name': 'DevSvc.exe', 'cmdline': None}
info:{'pid': 4028, 'name': 'svchost.exe', 'cmdline': None}
info:{'pid': 4072, 'name': 'ESPFSvc.exe', 'cmdline': None}
info:{'pid': 4084, 'name': 'ibtsiva.exe', 'cmdline': None}
info:{'pid': 4248, 'name': 'postgres.exe', 'cmdline': None}
info:{'pid': 4280, 'name': 'postgres.exe', 'cmdline': None}
info:{'pid': 4320, 'name': 'postgres.exe', 'cmdline': None}
info:{'pid': 4352, 'name': 'svchost.exe', 'cmdline': None}
```

Open only once when i run it in pycharm with no errors

**Comment by WK-GiHu** [comment]
@wan-joe 

>Open only once when i run it in pycharm with no errors
>Then print all the process running

Your outputs are all not relevant, becaus all are `info['cmdline'] == None`!
We are only interested in `info['cmdline']` with relevant data.

---

Next:
- [x] Merge my Pull request, to skipt all `info['cmdline'] == None`
- [ ] Run it **compiled** and show **only** the **ONE** output `info:{'pid': ???, ...}` with the matching `PID` from the output in `PROCNAME:C:/.../STARTTER PROJECT/APP.py PID:260628`

**Comment by wan-joe** [comment]
Getting this error
`NameError: name 'info' is not defined`

**Comment by WK-GiHu** [comment]
@wan-joe 

>Getting this error
>`NameError: name 'info' is not defined`

Unintentionally overwrote Line 22

- [ ] Merge my Pull request, or reinsert from **History**.

**Comment by wan-joe** [comment]
This is the output:

`PROCNAME:C:/Users/MARW\\MARW-LAP1/PycharmProjects/STARTTER PROJECT/APP.py PID:397300`


```
info:{'pid': 395868, 'cmdline': ['C:\\UsersMARW\\MARW-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}
info:{'pid': 396396, 'cmdline': ['C:\\UsersMARW\\MARW-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}
info:{'pid': 396604, 'cmdline': ['C:\\UsersMARW\\MARW-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}
info:{'pid': 397188, 'cmdline': ['C:\\UsersMARW\\MARW-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}

```

**Comment by WK-GiHu** [comment]
@wan-joe 

Don't forget, to notify me, using @WK-GiHu !

---

>This is the output:
>`PROCNAME:C:/.../PycharmProjects/STARTTER PROJECT/APP.py PID:397300`

This output are from `PycharmProjects` and not from the compiled version.

Running the compiled version:
- [x] I'm not able to see the output
- [ ] I'm able to see and copy the output fine

---

- [x] Merge my Pull request, **Version using hardcoded 'name': 'myapp.exe'**

**Comment by wan-joe** [comment]
`I'm not able to see the output`
Where can i see the output file when i run the `exe` don't see the output

**Comment by WK-GiHu** [comment]
@wan-joe 

>Where can i see the output file when i run the exe

You have to open a `Command Prompt` => [how-to-open-command-prompt](https://www.lifewire.com/how-to-open-command-prompt-2618089) and start the `exe` from there typing `<path to the exe file>\myapp.exe`.

**Comment by wan-joe** [comment]
After compiling the `exe` doesn't work when i click on it or from command prompt 

`Failed to execute script`

@WK-GiHu
